/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--color-surface-tint, #95d3ba)",
        "on-error-container": "var(--color-on-error-container, #ffdad6)",
        "surface-container-low": "var(--color-surface-container-low, #151b2d)",
        "on-error": "var(--color-on-error, #690005)",
        "tertiary": "var(--color-tertiary, #c4c7c9)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #2a3043)",
        "on-secondary": "var(--color-on-secondary, #532200)",
        "on-surface": "var(--color-on-surface, #dce1fb)",
        "inverse-primary": "var(--color-inverse-primary, #2b6954)",
        "error-container": "var(--color-error-container, #93000a)",
        "primary-container": "var(--color-primary-container, #064e3b)",
        "inverse-surface": "var(--color-inverse-surface, #dce1fb)",
        "error": "var(--color-error, #ffb4ab)",
        "surface-container-highest": "var(--color-surface-container-highest, #2e3447)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #95d3ba)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #331200)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #002117)",
        "background": "var(--color-background, #0c1324)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #191c1e)",
        "primary": "var(--color-primary, #95d3ba)",
        "outline": "var(--color-outline, #89938d)",
        "on-background": "var(--color-on-background, #dce1fb)",
        "outline-variant": "var(--color-outline-variant, #404944)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #e0e3e5)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #070d1f)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #444749)",
        "on-secondary-container": "var(--color-on-secondary-container, #ffe2d5)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #afb2b4)",
        "surface-container": "var(--color-surface-container, #191f31)",
        "surface": "var(--color-surface, #0c1324)",
        "surface-variant": "var(--color-surface-variant, #2e3447)",
        "on-surface-variant": "var(--color-on-surface-variant, #bfc9c3)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #763300)",
        "on-primary-container": "var(--color-on-primary-container, #80bea6)",
        "on-primary": "var(--color-on-primary, #003829)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #ffb68e)",
        "surface-dim": "var(--color-surface-dim, #0c1324)",
        "secondary": "var(--color-secondary, #ffb68e)",
        "secondary-fixed": "var(--color-secondary-fixed, #ffdbca)",
        "surface-bright": "var(--color-surface-bright, #33394c)",
        "on-tertiary": "var(--color-on-tertiary, #2d3133)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #c4c7c9)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #0b513d)",
        "primary-fixed": "var(--color-primary-fixed, #b0f0d6)",
        "surface-container-high": "var(--color-surface-container-high, #23293c)",
        "secondary-container": "var(--color-secondary-container, #ab4c00)",
        "tertiary-container": "var(--color-tertiary-container, #424547)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "40px",
        "margin-desktop": "48px",
        unit: "4px",
        gutter: "24px",
        sm: "8px",
        lg: "24px",
        md: "16px",
        "margin-mobile": "16px",
        xs: "4px",
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
